name: 'sd_police_stops'
version: '1.0.0'

profile: 'ripa_police_data'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  sd_police_stops:
    staging:
      ripa:
        +enabled: true
        +materialized: view