version: 2

sources:
  - name: raw
    schema: ripa  # BigQuery dataset name
    tables:
      - name: raw_ripa_stops_datasd
      - name: raw_ripa_contraband_evid_datasd
      - name: raw_ripa_disability_datasd
      - name: raw_ripa_force_actions_datasd
      - name: raw_ripa_nonforce_actions_datasd
      - name: raw_ripa_prop_seize_basis_datasd
      - name: raw_ripa_prop_seize_type_datasd
      - name: raw_ripa_race_datasd
      - name: raw_ripa_search_basis_datasd
      - name: raw_ripa_stop_reason_datasd
      - name: raw_ripa_stop_result_datasd
